### ISSUE TITLE
Users can make data visualizations on found sets

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1664]
Users can use the search to limit their found set, and then take the data for all of the records in their found set and put it into various data visualization views.

- [ ] Search results page has a way to get directly to data visualization space
- [ ] When the user gets into the data visualization space, that space knows about the found set they had 
- [ ] The user can select from various data visualization types that are created using something like https://d3js.org/

**Comment by mccalluc** [comment]
Howdy! I'm not sure if it's on your radar, but I experimented with making some visualizations with AAPB data way back when: http://mccalluc.github.io/alt-aapb/

(They are hitting an API endpoint on AAPB I created, and 2/3 still seem to work, though the presidential example looks different than my screen shot because you've added records.)

**Comment by sroosa** [comment]
@mccalluc We are actually using your visualization as an example to show people what type of data visualization can be done with AAPB! We're pursuing grants to help us make both our data more robust and to help users create additional visualization using the data! It's been great to have something people can actually see as an example. 

Hope you're doing well!!!!

**Comment by ekemeyer** [comment]
-
