### ISSUE TITLE
Batch add PBS Learning Media links to selected NewsHour records

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2038]
##User Story
A user should see an accordion heading called "Supplemental Material" which contains a link called PBS Learning Media Resource and links to the specified learning object.

![Screen Shot 2020-05-18 at 1.03.12 PM.png](https://images.zenhubusercontent.com/5e5e7f2e572e74e6537e269f/1d12d929-ce9f-4b00-bcbb-4d0d3eb66906)

## Done When

The linked text "PBS Learning Media Resource" links back to the correct learning resource. AAPB items are in column F and the PBS Learning Media URL is in column K of this spreadsheet. [https://docs.google.com/spreadsheets/d/1GAwDybOqDniJrNijlVWOWTauxaeYgvyd0lv3mwzVULg/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1GAwDybOqDniJrNijlVWOWTauxaeYgvyd0lv3mwzVULg/edit?usp=sharing)

**Comment by singlesoliloquy** [comment]
Check out Ryn's Round two as first step.

**Comment by jasoncorum** [comment]
we have functionality in place to display “Supplemental Materials” on AAPB as described. it’s not in use a whole lot, but you can check it out here. https://americanarchive.org/catalog/cpb-aacip-509-6h4cn6zm21. the functionality is tied to a pbcoreAnnotation (per usual…), but for the “bulk add” part do we need to be able to manage this annotation in ams and push to AAPB?

**Comment by jasoncorum** [comment]
We're going to re-envision how we handle PBCore annotations on AMS2. We discussed this morning and we're going to create a new table for annotations within AMS2 where we can set all the various attributes (http://pbcore.org/elements/pbcoreannotation). As part of this work we will:

- [ ] Create a picklist for the annotationType, so that we can control the types we can export to external systems.
- [ ] The annotation is related to an Asset's AdminData so that one AdminData object has_many Annotations and an Annotation belongs_to an AdminData object.
- [ ] Migrate Annotation data that has been applied via single value attribute on the AdminData object to a new Annotation object.
- [ ] We can import and export these annotations via PBCore

**Comment by jasoncorum** [comment]
**Step by Step for releasing AMS Annotation Migration**

1. Release the 2038_annotations branch to the instance
2. run the rake task on the AMS web machine:
    1. RAILS_ENV=production bundle exec rake ams:annotation_migration --trace > rake.out 2>&1 &
        1. You can follow along by tailing the rake.out file
        2. This will take a long time to around ~8-10 hours
3. Create a new Rails db migration that removes the following columns from AdminData
    1. :level_of_user_access, :minimally_cataloged, :outside_url, :special_collection, :transcript_status, :licensing_info, :playlist_group, :playlist_order, :organization, :special_collection_category, :canonical_meta_tag
4. Remove/update code marked for deletion/update in comments.
    1. asset_actor.rb, asset_form.rb, admin_data.rb, asset.rb

**Comment by jasoncorum** [comment]
This functionality is in place, but I'm not seeing Supplemental Materials added yet, so waiting to fully close.
