### ISSUE TITLE
Batch Upload to Sony Ci

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/AAPB2#2256]
Currently, archivists are downloading and running a local copy the AAPB2 application in order to batch upload media files to Sony Ci using the `ci.rb` script. The primary reason archivists are uploading files this way is that the `ci.rb` scripts provides a log file `ci_log.tab` that provides the archivist with a mapping between the cpb-aacip-* ID and the Sony Ci ID which is created once a file is uploaded. Accessing this information via the UI isn't user friendly. The cpb-aacip-* ID is used as filename for the Ci asset.

Unfortunately, this process requires archivists to get an entire ruby environment up and running locally which is difficult given IT constraints and variations within local environments. We'd like to provide a better solution that doesn't require all of this setup.

This is a research ticket to chart a way forward and these are some of the questions we've identified that would help craft a solution.

**Done When** We answer these questions and propose a new solution.

1. Does uploading batches of media via the Sony Ci interface or Aspera meet our uploading needs and performance?
2. Can we get the Sony Ci ID from the Sony Ci API and tie it to the cpb-aacip-* filename? Looks like yes.
3. Can we reduce or eliminate the need for our Sony CI gem? https://github.com/WGBH-MLA/sony_ci_api

Once we get these questions answered, we can hopefully craft a solution that doesn't require setting up a working ruby environment on individuals' laptops.

**Comment by afred** [comment]
I think this can be closed. The answer to the **done when** criteria are as follows:

1. Yes
2. Yes - Not only can we query Sony Ci with a GUID to look for matching Sony Ci filenames, but we can tie into Sony Ci's webhooks, which I have since implemented.
3. Yes. In the process of #2, I created a rewrite of the Sony Ci gem, which is now better organized, better tested, and more flexible to extend to any part of the Sony Ci api we want with ease. The one caveat is not all of the features of the old `sony_ci_api` gem have been implemented yet, namely multipart upload. But if #2 works, then we won't need to use the gem to upload as part of our workflow.

Currently the idea in progress is to:
1. Use Sony Ci webhooks and a new API endpoint to automatically link newly uploaded Sony Ci files to existing AMS Assets.
2. Provide a feature to search Sony Ci for a filename that matches a given GUID, and gives archivists the option to link the found Sony Ci IDs to the AMS Asset.
