### ISSUE TITLE
Change "Watch from Here" to "Access from Here"

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#2452]
## User Story
As a user, when I do a search of the AAPB and the keywords appear in a transcript, I should see a link that says "Access from Here" rather than "Watch from Here" since not all content in the AAPB is TV. 

<img width="960" alt="Snap9 (1)" src="https://user-images.githubusercontent.com/5992135/180262184-27db8969-3483-47db-8479-46d848f1b143.png">

**Comment by mrharpo** [comment]
It looks like the code already does this, at least a little:
From https://github.com/WGBH-MLA/AAPB2/issues/1667#issuecomment-574849968
> Have the text read "Watch from here" or "Listen from here"

And in [snippet_helper.rb](https://github.com/WGBH-MLA/AAPB2/blob/0a3882b2662bec3b094ab8474db0c83454b1a1fd/app/helpers/snippet_helper.rb#L7), it renders:
```html
<button type="button" class="btn btn-default snippet-link">#{media_type == 'Moving Image' ? "Watch" : "Listen"} from here</button>
```

**Comment by caseyedavis12** [comment]
Hmmm... here is an example of a radio series where the button says "Watch  from Here" 

https://americanarchive.org/catalog?f%5Bspecial_collections%5D%5B%5D=backstory&q=aids&sort=asset_date+asc&utf8=%E2%9C%93&f[access_types][]=online

**Comment by mrharpo** [comment]
Very strange!

Here is that record you found:
https://americanarchive.org/catalog/cpb-aacip-532-3r0pr7nx4w

But the `.pbcore` says:
```xml
<instantiationMediaType>Sound</instantiationMediaType>
```

**Comment by mrharpo** [comment]
It looks like the `media_type` is always set to `"Moving Image"`, and does not come from the type of media:

https://github.com/WGBH-MLA/AAPB2/blob/0a3882b2662bec3b094ab8474db0c83454b1a1fd/app/controllers/snippets_controller.rb#L36-L46

**Comment by foglabs** [comment]
@mrharpo you're right, it'll always get set to 'Moving Image' - I think this is an oversight from my last refactor 😬 

if you wanted to maintain the old behavior for this, you would need to get the xml from the SolrDocument, use it to instantiate a  `PBCorePresenter`, and then pass in `your_pbcoreprsenter_instance.media_type` instead of "Moving Image"

I think casey's change to 'Access' is better here, because there's actually a lot of processing and loading that happens during `PBCorePresenter.new(xml)`, and this snippet code will potentially be run once for each record in every page of a catalog search.
