### ISSUE TITLE
Formatting description and transcripts when they exist

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#340]
If I am a user accessing the website, I would like to be able to read well-formatted descriptions and transcripts when they exist.

**Comment by mccalluc** [comment]
By "transcript" you mean records like http://americanarchive.org/catalog/cpb-aacip_215-32r4xnmx.pbcore where a transcript is in the pbcoreDescription? Or are we talking about an entirely new kind of data that will be ingested?

We're somewhat constrained here
- because the XSD descriptionStringType is just a string: we shouldn't try to cram markup in there.
- and because this is not a matter of preserving information, it's a matter of recreating the data which is missing.

**proposal**
- Identify a subset of records where we think formatting would help (rather than applying across the board).
- As part of cleaning on ingest, use regexes to insert newlines in particular records.
- Have the UI respect these newlines.
- Reindex all records for this to take effect.

**Comment by caseyedavis12** [comment]
This is very low priority.

Yes, I am talking about records that have a transcripts in the PBCore Description, like the record you referenced.

proposal

  *   Identify a subset of records where we think formatting would help (rather than applying across the board). --> WHYY submitted a lot of transcripts in their data
  *   As part of cleaning on ingest, use regexes to insert newlines in particular records.
  *   Have the UI respect these newlines.
  *   Reindex all records for this to take effect.
