### ISSUE TITLE
Replace lib/rails_stub.rb with a constant, or something else.

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#523]
reasoning:
1. I think we only needed the "stub" because something was trying to use`Rails.root` without needing the rest of `Rails` as a dependency. If all we need is a path, then let's just use a constant. Or if we're ok depending on `Rack`, then use `Rack::Directory.new('').root`.
2. Calling it a "stub" is misleading anyway, because there is a Rails binstub under `bin/rails` that is something totally different.

**Comment by mccalluc** [comment]
If there's a better idiom, great. `Rails.root` is, as far as I know, the most concise/idiomatic expression -- I just didn't want the overhead of loading Rails each time if I'm just trying to get one particular test to pass.

I guess we could do a search and replace and go with something else... but then new code has to remember what our particular idiom is, instead of going with the most obvious choice. I have no attachment to "stub" in the filename: It could be anything.
